spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  profiles:
    include: dev

